import fs from 'fs';
import path from 'path';
import { icons as lucideIcons } from 'lucide';

function findLucideImports(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    if (file === 'node_modules' || file === '.git' || file === 'dist') continue;
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      findLucideImports(filePath, fileList);
    } else if (filePath.endsWith('.tsx') || filePath.endsWith('.ts')) {
      const content = fs.readFileSync(filePath, 'utf-8');
      if (content.includes('lucide-react')) {
        fileList.push(filePath);
      }
    }
  }
  return fileList;
}

const files = findLucideImports('.');
const icons = new Set();

for (const file of files) {
  const content = fs.readFileSync(file, 'utf-8');
  const lines = content.split('\n');
  for (const line of lines) {
    if (line.includes('lucide-react')) {
      const match = line.match(/import\s+\{([^}]+)\}\s+from\s+['"]lucide-react['"]/);
      if (match) {
        const importedIcons = match[1].split(',').map(i => i.trim()).filter(i => i);
        for (const icon of importedIcons) {
            const iconName = icon.split(' as ')[0].trim();
            icons.add(iconName);
        }
      }
    }
  }
}

let output = `// Auto-generated by generate_icons.ts
import React from 'react';

export type IconName = ${Array.from(icons).map(i => "'" + i + "'").join(' | ')};

export const iconData: Record<IconName, any[]> = {
`;

for (const iconName of Array.from(icons).sort()) {
    const data = lucideIcons[iconName];
    if (data) {
        output += `  '${iconName}': ${JSON.stringify(data)},\n`;
    } else {
        console.warn(`Icon ${iconName} not found in lucide data`);
    }
}

output += `};

export const Icon = ({ name, className, ...props }: { name: IconName; className?: string } & React.SVGProps<SVGSVGElement>) => {
  const data = iconData[name];
  if (!data) return null;
  
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      {...props}
    >
      {data.map(([tag, attrs], i) => {
        const Tag = tag as any;
        return <Tag key={i} {...attrs} />;
      })}
    </svg>
  );
};
`;

fs.writeFileSync('components/shared/Icon.tsx', output);
console.log('Generated components/shared/Icon.tsx');
